apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mydemos.crddemo.k8s.io
spec:
  group: crddemo.k8s.io
  version: v1
  names:
    kind: Mydemo
    plural: mydemos
  scope: Namespaced
